version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ai-ready-bi-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: lms_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - postgres

volumes:
  postgres_data: